from .core import (
    FailureStage,
    FailureType,
    PipelineTrace,
    FailureRecord,
    DiagnosticBenchmark,
    KnowledgeNode,
    KnowledgeGraph,
    AgenticRAGPipeline,
    reformulate_query,
)
from .evaluate import (
    stage_attribution_rate,
    propagation_rate,
    failure_confusion_matrix,
    root_cause_stage,
    root_cause_accuracy,
    end_to_end_accuracy,
    severity_weighted_failure_rate,
    multi_hop_accuracy,
    retrieval_loop_efficiency,
    mean_hops_per_trace,
    hop_doc_coverage,
    failure_amplification_rate,
    recovery_rate,
    answer_token_recall,
    answer_em_score,
    mean_answer_recall,
    mean_answer_em,
    diagnosis_correct,
    localization_accuracy,
    mean_localization_error,
    attribution_identifiability,
    cost_per_correct_diagnosis,
    rescore_identifiability,
    ancestor_hit,
    ancestor_hit_rate,
    bootstrap_localization_ci,
    slice_identifiability,
    corruption_absorption_rates,
)
from .corruption import (
    CorruptionRecord,
    select_target_span,
    make_replacement,
    corrupt_docs,
    classify_absorption,
)
from .data import make_trace, make_dataset, make_multi_hop_trace, build_knowledge_graph, make_multi_hop_corpus
from .retrievers import BM25Retriever, TokenOverlapRetriever, DenseRetriever
from .datasets import (
    QASample,
    load_hotpotqa,
    load_musique,
    load_frames,
    load_crag,
    load_dataset,
    iter_batches,
    frames_corpus_stats,
)
from .agents import (
    LLMResponse,
    LLMProvider,
    ClaudeProvider,
    OpenAIProvider,
    MockProvider,
    make_provider,
    AgentDecision,
    parse_decision,
    HopState,
    LLMAgent,
)
from .injection import (
    FailureInjector,
    InjectionResult,
    injection_sensitivity,
    LiveFailureInjector,
    LIVE_INJECTIONS,
)
from .diagnosers import (
    Diagnosis,
    Diagnoser,
    RuleBasedDiagnoser,
    DoctorRAGDiagnoser,
    LLMJudgeDiagnoser,
    PropagationAwareDiagnoser,
    SuffixRegenerationDiagnoser,
    batch_diagnose,
)
from .experiment import (
    AblationCell,
    AblationResult,
    run_ablation,
    IdentifiabilityResult,
    run_identifiability,
    HOP_METHODS,
    ANSWER_METHODS,
    ALL_METHODS,
)
from .propagation import PropagationEdge, PropagationGraph, counterfactual_recovery_rate

__all__ = [
    # Core models
    "FailureStage",
    "FailureType",
    "PipelineTrace",
    "FailureRecord",
    "DiagnosticBenchmark",
    "KnowledgeNode",
    "KnowledgeGraph",
    "AgenticRAGPipeline",
    "reformulate_query",
    # Evaluation metrics
    "stage_attribution_rate",
    "propagation_rate",
    "failure_confusion_matrix",
    "root_cause_stage",
    "root_cause_accuracy",
    "end_to_end_accuracy",
    "severity_weighted_failure_rate",
    "multi_hop_accuracy",
    "retrieval_loop_efficiency",
    "mean_hops_per_trace",
    "hop_doc_coverage",
    "failure_amplification_rate",
    "recovery_rate",
    "answer_token_recall",
    "answer_em_score",
    "mean_answer_recall",
    "mean_answer_em",
    "diagnosis_correct",
    "localization_accuracy",
    "mean_localization_error",
    "attribution_identifiability",
    "cost_per_correct_diagnosis",
    "rescore_identifiability",
    "ancestor_hit",
    "ancestor_hit_rate",
    "bootstrap_localization_ci",
    "slice_identifiability",
    "corruption_absorption_rates",
    # Content corruption (certified spans + deterministic generation eval)
    "CorruptionRecord",
    "select_target_span",
    "make_replacement",
    "corrupt_docs",
    "classify_absorption",
    # Synthetic data
    "make_trace",
    "make_dataset",
    "make_multi_hop_trace",
    "build_knowledge_graph",
    "make_multi_hop_corpus",
    # Retrievers
    "BM25Retriever",
    "TokenOverlapRetriever",
    "DenseRetriever",
    # Dataset adapters
    "QASample",
    "load_hotpotqa",
    "load_musique",
    "load_frames",
    "load_crag",
    "load_dataset",
    "iter_batches",
    "frames_corpus_stats",
    # Real LLM agent
    "LLMResponse",
    "LLMProvider",
    "ClaudeProvider",
    "OpenAIProvider",
    "MockProvider",
    "make_provider",
    "AgentDecision",
    "parse_decision",
    "HopState",
    "LLMAgent",
    # Failure injection
    "FailureInjector",
    "InjectionResult",
    "injection_sensitivity",
    "LiveFailureInjector",
    "LIVE_INJECTIONS",
    # Diagnosers
    "Diagnosis",
    "Diagnoser",
    "RuleBasedDiagnoser",
    "DoctorRAGDiagnoser",
    "LLMJudgeDiagnoser",
    "PropagationAwareDiagnoser",
    "SuffixRegenerationDiagnoser",
    "batch_diagnose",
    # Ablation experiment runner
    "AblationCell",
    "AblationResult",
    "run_ablation",
    "IdentifiabilityResult",
    "run_identifiability",
    "HOP_METHODS",
    "ANSWER_METHODS",
    "ALL_METHODS",
    # Propagation graph
    "PropagationEdge",
    "PropagationGraph",
    "counterfactual_recovery_rate",
]
